local function SetupFreeImage()
    local basePath = path.getabsolute("Cuttlefish/Cuttlefish", AssetConverter.dependencyDir)
    local freeImageRootDir = path.getabsolute("lib/FreeImage", basePath)

    local files =
    {
        freeImageRootDir .. "/Source/FreeImage/BitmapAccess.cpp",
        freeImageRootDir .. "/Source/FreeImage/ColorLookup.cpp",
        freeImageRootDir .. "/Source/FreeImage/ConversionRGBA16.cpp",
        freeImageRootDir .. "/Source/FreeImage/ConversionRGBAF.cpp",
        freeImageRootDir .. "/Source/FreeImage/FreeImage.cpp",
        freeImageRootDir .. "/Source/FreeImage/FreeImageC.c",
        freeImageRootDir .. "/Source/FreeImage/FreeImageIO.cpp",
        freeImageRootDir .. "/Source/FreeImage/GetType.cpp",
        freeImageRootDir .. "/Source/FreeImage/LFPQuantizer.cpp",
        freeImageRootDir .. "/Source/FreeImage/MemoryIO.cpp",
        freeImageRootDir .. "/Source/FreeImage/PixelAccess.cpp",
        freeImageRootDir .. "/Source/FreeImage/J2KHelper.cpp",
        freeImageRootDir .. "/Source/FreeImage/MNGHelper.cpp",
        freeImageRootDir .. "/Source/FreeImage/Plugin.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginBMP.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginCUT.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginDDS.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginEXR.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginG3.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginGIF.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginHDR.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginICO.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginIFF.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginJ2K.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginJNG.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginJP2.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginJPEG.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginJXR.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginKOALA.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginMNG.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginPCD.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginPCX.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginPFM.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginPICT.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginPNG.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginPNM.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginPSD.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginRAS.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginRAW.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginSGI.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginTARGA.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginTIFF.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginWBMP.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginWebP.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginXBM.cpp",
        freeImageRootDir .. "/Source/FreeImage/PluginXPM.cpp",
        freeImageRootDir .. "/Source/FreeImage/PSDParser.cpp",
        freeImageRootDir .. "/Source/FreeImage/TIFFLogLuv.cpp",
        freeImageRootDir .. "/Source/FreeImage/Conversion.cpp",
        freeImageRootDir .. "/Source/FreeImage/Conversion16_555.cpp",
        freeImageRootDir .. "/Source/FreeImage/Conversion16_565.cpp",
        freeImageRootDir .. "/Source/FreeImage/Conversion24.cpp",
        freeImageRootDir .. "/Source/FreeImage/Conversion32.cpp",
        freeImageRootDir .. "/Source/FreeImage/Conversion4.cpp",
        freeImageRootDir .. "/Source/FreeImage/Conversion8.cpp",
        freeImageRootDir .. "/Source/FreeImage/ConversionFloat.cpp",
        freeImageRootDir .. "/Source/FreeImage/ConversionRGB16.cpp",
        freeImageRootDir .. "/Source/FreeImage/ConversionRGBF.cpp",
        freeImageRootDir .. "/Source/FreeImage/ConversionType.cpp",
        freeImageRootDir .. "/Source/FreeImage/ConversionUINT16.cpp",
        freeImageRootDir .. "/Source/FreeImage/Halftoning.cpp",
        freeImageRootDir .. "/Source/FreeImage/tmoColorConvert.cpp",
        freeImageRootDir .. "/Source/FreeImage/tmoDrago03.cpp",
        freeImageRootDir .. "/Source/FreeImage/tmoFattal02.cpp",
        freeImageRootDir .. "/Source/FreeImage/tmoReinhard05.cpp",
        freeImageRootDir .. "/Source/FreeImage/ToneMapping.cpp",
        freeImageRootDir .. "/Source/FreeImage/NNQuantizer.cpp",
        freeImageRootDir .. "/Source/FreeImage/WuQuantizer.cpp",
        freeImageRootDir .. "/Source/FreeImage/CacheFile.cpp",
        freeImageRootDir .. "/Source/FreeImage/MultiPage.cpp",
        freeImageRootDir .. "/Source/FreeImage/ZLibInterface.cpp",
        freeImageRootDir .. "/Source/Metadata/Exif.cpp",
        freeImageRootDir .. "/Source/Metadata/FIRational.cpp",
        freeImageRootDir .. "/Source/Metadata/FreeImageTag.cpp",
        freeImageRootDir .. "/Source/Metadata/IPTC.cpp",
        freeImageRootDir .. "/Source/Metadata/TagConversion.cpp",
        freeImageRootDir .. "/Source/Metadata/TagLib.cpp",
        freeImageRootDir .. "/Source/Metadata/XTIFF.cpp",
        freeImageRootDir .. "/Source/FreeImageToolkit/Background.cpp",
        freeImageRootDir .. "/Source/FreeImageToolkit/BSplineRotate.cpp",
        freeImageRootDir .. "/Source/FreeImageToolkit/Channels.cpp",
        freeImageRootDir .. "/Source/FreeImageToolkit/ClassicRotate.cpp",
        freeImageRootDir .. "/Source/FreeImageToolkit/Colors.cpp",
        freeImageRootDir .. "/Source/FreeImageToolkit/CopyPaste.cpp",
        freeImageRootDir .. "/Source/FreeImageToolkit/Display.cpp",
        freeImageRootDir .. "/Source/FreeImageToolkit/Flip.cpp",
        freeImageRootDir .. "/Source/FreeImageToolkit/JPEGTransform.cpp",
        freeImageRootDir .. "/Source/FreeImageToolkit/MultigridPoissonSolver.cpp",
        freeImageRootDir .. "/Source/FreeImageToolkit/Rescale.cpp",
        freeImageRootDir .. "/Source/FreeImageToolkit/Resize.cpp",
        freeImageRootDir .. "/Source/LibJPEG/jaricom.c",
        freeImageRootDir .. "/Source/LibJPEG/jcapimin.c",
        freeImageRootDir .. "/Source/LibJPEG/jcapistd.c",
        freeImageRootDir .. "/Source/LibJPEG/jcarith.c",
        freeImageRootDir .. "/Source/LibJPEG/jccoefct.c",
        freeImageRootDir .. "/Source/LibJPEG/jccolor.c",
        freeImageRootDir .. "/Source/LibJPEG/jcdctmgr.c",
        freeImageRootDir .. "/Source/LibJPEG/jchuff.c",
        freeImageRootDir .. "/Source/LibJPEG/jcinit.c",
        freeImageRootDir .. "/Source/LibJPEG/jcmainct.c",
        freeImageRootDir .. "/Source/LibJPEG/jcmarker.c",
        freeImageRootDir .. "/Source/LibJPEG/jcmaster.c",
        freeImageRootDir .. "/Source/LibJPEG/jcomapi.c",
        freeImageRootDir .. "/Source/LibJPEG/jcparam.c",
        freeImageRootDir .. "/Source/LibJPEG/jcprepct.c",
        freeImageRootDir .. "/Source/LibJPEG/jcsample.c",
        freeImageRootDir .. "/Source/LibJPEG/jctrans.c",
        freeImageRootDir .. "/Source/LibJPEG/jdapimin.c",
        freeImageRootDir .. "/Source/LibJPEG/jdapistd.c",
        freeImageRootDir .. "/Source/LibJPEG/jdarith.c",
        freeImageRootDir .. "/Source/LibJPEG/jdatadst.c",
        freeImageRootDir .. "/Source/LibJPEG/jdatasrc.c",
        freeImageRootDir .. "/Source/LibJPEG/jdcoefct.c",
        freeImageRootDir .. "/Source/LibJPEG/jdcolor.c",
        freeImageRootDir .. "/Source/LibJPEG/jddctmgr.c",
        freeImageRootDir .. "/Source/LibJPEG/jdhuff.c",
        freeImageRootDir .. "/Source/LibJPEG/jdinput.c",
        freeImageRootDir .. "/Source/LibJPEG/jdmainct.c",
        freeImageRootDir .. "/Source/LibJPEG/jdmarker.c",
        freeImageRootDir .. "/Source/LibJPEG/jdmaster.c",
        freeImageRootDir .. "/Source/LibJPEG/jdmerge.c",
        freeImageRootDir .. "/Source/LibJPEG/jdpostct.c",
        freeImageRootDir .. "/Source/LibJPEG/jdsample.c",
        freeImageRootDir .. "/Source/LibJPEG/jdtrans.c",
        freeImageRootDir .. "/Source/LibJPEG/jerror.c",
        freeImageRootDir .. "/Source/LibJPEG/jfdctflt.c",
        freeImageRootDir .. "/Source/LibJPEG/jfdctfst.c",
        freeImageRootDir .. "/Source/LibJPEG/jfdctint.c",
        freeImageRootDir .. "/Source/LibJPEG/jidctflt.c",
        freeImageRootDir .. "/Source/LibJPEG/jidctfst.c",
        freeImageRootDir .. "/Source/LibJPEG/jidctint.c",
        freeImageRootDir .. "/Source/LibJPEG/jmemmgr.c",
        freeImageRootDir .. "/Source/LibJPEG/jmemnobs.c",
        freeImageRootDir .. "/Source/LibJPEG/jquant1.c",
        freeImageRootDir .. "/Source/LibJPEG/jquant2.c",
        freeImageRootDir .. "/Source/LibJPEG/jutils.c",
        freeImageRootDir .. "/Source/LibJPEG/transupp.c",
        freeImageRootDir .. "/Source/LibPNG/png.c",
        freeImageRootDir .. "/Source/LibPNG/pngerror.c",
        freeImageRootDir .. "/Source/LibPNG/pngget.c",
        freeImageRootDir .. "/Source/LibPNG/pngmem.c",
        freeImageRootDir .. "/Source/LibPNG/pngpread.c",
        freeImageRootDir .. "/Source/LibPNG/pngread.c",
        freeImageRootDir .. "/Source/LibPNG/pngrio.c",
        freeImageRootDir .. "/Source/LibPNG/pngrtran.c",
        freeImageRootDir .. "/Source/LibPNG/pngrutil.c",
        freeImageRootDir .. "/Source/LibPNG/pngset.c",
        freeImageRootDir .. "/Source/LibPNG/pngtrans.c",
        freeImageRootDir .. "/Source/LibPNG/pngwio.c",
        freeImageRootDir .. "/Source/LibPNG/pngwrite.c",
        freeImageRootDir .. "/Source/LibPNG/pngwtran.c",
        freeImageRootDir .. "/Source/LibPNG/pngwutil.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_aux.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_close.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_codec.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_color.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_compress.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_dir.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_dirinfo.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_dirread.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_dirwrite.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_dumpmode.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_error.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_extension.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_fax3.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_fax3sm.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_flush.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_getimage.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_hash_set.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_jpeg.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_lerc.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_luv.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_lzw.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_next.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_ojpeg.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_open.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_packbits.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_pixarlog.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_predict.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_print.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_read.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_strip.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_swab.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_thunder.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_tile.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_version.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_warning.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_webp.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_write.c",
        freeImageRootDir .. "/Source/LibTIFF4/tif_zip.c",
        freeImageRootDir .. "/Source/ZLib/adler32.c",
        freeImageRootDir .. "/Source/ZLib/compress.c",
        freeImageRootDir .. "/Source/ZLib/crc32.c",
        freeImageRootDir .. "/Source/ZLib/deflate.c",
        freeImageRootDir .. "/Source/ZLib/gzclose.c",
        freeImageRootDir .. "/Source/ZLib/gzlib.c",
        freeImageRootDir .. "/Source/ZLib/gzread.c",
        freeImageRootDir .. "/Source/ZLib/gzwrite.c",
        freeImageRootDir .. "/Source/ZLib/infback.c",
        freeImageRootDir .. "/Source/ZLib/inffast.c",
        freeImageRootDir .. "/Source/ZLib/inflate.c",
        freeImageRootDir .. "/Source/ZLib/inftrees.c",
        freeImageRootDir .. "/Source/ZLib/trees.c",
        freeImageRootDir .. "/Source/ZLib/uncompr.c",
        freeImageRootDir .. "/Source/ZLib/zutil.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/bio.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/cio.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/dwt.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/event.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/function_list.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/image.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/invert.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/j2k.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/jp2.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/mct.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/mqc.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/openjpeg.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/opj_clock.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/pi.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/raw.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/t1.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/t2.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/tcd.c",
        freeImageRootDir .. "/Source/LibOpenJPEG/tgt.c",
        freeImageRootDir .. "/Source/OpenEXR/IexMath/IexMathFpu.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfAcesFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfB44Compressor.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfBoxAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfChannelList.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfChannelListAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfChromaticities.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfChromaticitiesAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfCompositeDeepScanLine.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfCompressionAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfCompressor.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfConvert.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfCRgbaFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfDeepCompositing.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfDeepFrameBuffer.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfDeepImageStateAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfDeepScanLineInputFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfDeepScanLineInputPart.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfDeepScanLineOutputFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfDeepScanLineOutputPart.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfDeepTiledInputFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfDeepTiledInputPart.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfDeepTiledOutputFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfDeepTiledOutputPart.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfDoubleAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfDwaCompressor.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfEnvmap.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfEnvmapAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfFastHuf.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfFloatAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfFloatVectorAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfFrameBuffer.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfFramesPerSecond.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfGenericInputFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfGenericOutputFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfHeader.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfHuf.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfInputFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfInputPart.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfInputPartData.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfIntAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfIO.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfKeyCode.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfKeyCodeAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfLineOrderAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfLut.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfMatrixAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfMisc.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfMultiPartInputFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfMultiPartOutputFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfMultiView.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfOpaqueAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfOutputFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfOutputPart.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfOutputPartData.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfPartType.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfPizCompressor.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfPreviewImage.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfPreviewImageAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfPxr24Compressor.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfRational.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfRationalAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfRgbaFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfRgbaYca.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfRle.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfRleCompressor.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfScanLineInputFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfStandardAttributes.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfStdIO.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfStringAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfStringVectorAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfSystemSpecific.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfTestFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfThreading.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfTileDescriptionAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfTiledInputFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfTiledInputPart.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfTiledMisc.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfTiledOutputFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfTiledOutputPart.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfTiledRgbaFile.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfTileOffsets.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfTimeCode.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfTimeCodeAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfVecAttribute.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfVersion.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfWav.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfZip.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf/ImfZipCompressor.cpp",
        freeImageRootDir .. "/Source/OpenEXR/Imath/ImathBox.cpp",
        freeImageRootDir .. "/Source/OpenEXR/Imath/ImathColorAlgo.cpp",
        freeImageRootDir .. "/Source/OpenEXR/Imath/ImathFun.cpp",
        freeImageRootDir .. "/Source/OpenEXR/Imath/ImathMatrixAlgo.cpp",
        freeImageRootDir .. "/Source/OpenEXR/Imath/ImathRandom.cpp",
        freeImageRootDir .. "/Source/OpenEXR/Imath/ImathShear.cpp",
        freeImageRootDir .. "/Source/OpenEXR/Imath/ImathVec.cpp",
        freeImageRootDir .. "/Source/OpenEXR/Iex/IexBaseExc.cpp",
        freeImageRootDir .. "/Source/OpenEXR/Iex/IexThrowErrnoExc.cpp",
        freeImageRootDir .. "/Source/OpenEXR/Half/half.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmThread/IlmThread.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmThread/IlmThreadMutex.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmThread/IlmThreadPool.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IlmThread/IlmThreadSemaphore.cpp",
        freeImageRootDir .. "/Source/OpenEXR/IexMath/IexMathFloatExc.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/decoders/canon_600.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/decoders/crx.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/decoders/decoders_dcraw.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/decoders/decoders_libraw.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/decoders/decoders_libraw_dcrdefs.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/decoders/dng.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/decoders/fp_dng.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/decoders/fuji_compressed.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/decoders/generic.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/decoders/kodak_decoders.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/decoders/load_mfbacks.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/decoders/smal.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/decoders/unpack.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/decoders/unpack_thumb.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/demosaic/aahd_demosaic.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/demosaic/ahd_demosaic.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/demosaic/dcb_demosaic.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/demosaic/dht_demosaic.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/demosaic/misc_demosaic.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/demosaic/xtrans_demosaic.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/integration/dngsdk_glue.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/integration/rawspeed_glue.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/libraw_datastream.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/adobepano.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/canon.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/ciff.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/cr3_parser.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/epson.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/exif_gps.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/fuji.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/hasselblad_model.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/identify.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/identify_tools.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/kodak.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/leica.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/makernotes.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/mediumformat.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/minolta.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/misc_parsers.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/nikon.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/normalize_model.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/olympus.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/p1.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/pentax.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/samsung.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/sony.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/metadata/tiff.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/postprocessing/aspect_ratio.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/postprocessing/dcraw_process.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/postprocessing/mem_image.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/postprocessing/postprocessing_aux.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/postprocessing/postprocessing_utils.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/postprocessing/postprocessing_utils_dcrdefs.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/preprocessing/ext_preprocess.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/preprocessing/raw2image.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/preprocessing/subtract_black.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/tables/cameralist.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/tables/colorconst.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/tables/colordata.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/tables/wblists.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/utils/curves.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/utils/decoder_info.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/utils/init_close_utils.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/utils/open.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/utils/phaseone_processing.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/utils/read_utils.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/utils/thumb_utils.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/utils/utils_dcraw.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/utils/utils_libraw.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/write/file_write.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/x3f/x3f_parse_process.cpp",
        freeImageRootDir .. "/Source/LibRawLite/src/x3f/x3f_utils_patched.cpp",
        freeImageRootDir .. "/Source/LibWebP/src/dec/alpha_dec.c",
        freeImageRootDir .. "/Source/LibWebP/src/dec/buffer_dec.c",
        freeImageRootDir .. "/Source/LibWebP/src/dec/frame_dec.c",
        freeImageRootDir .. "/Source/LibWebP/src/dec/idec_dec.c",
        freeImageRootDir .. "/Source/LibWebP/src/dec/io_dec.c",
        freeImageRootDir .. "/Source/LibWebP/src/dec/quant_dec.c",
        freeImageRootDir .. "/Source/LibWebP/src/dec/tree_dec.c",
        freeImageRootDir .. "/Source/LibWebP/src/dec/vp8l_dec.c",
        freeImageRootDir .. "/Source/LibWebP/src/dec/vp8_dec.c",
        freeImageRootDir .. "/Source/LibWebP/src/dec/webp_dec.c",
        freeImageRootDir .. "/Source/LibWebP/src/demux/anim_decode.c",
        freeImageRootDir .. "/Source/LibWebP/src/demux/demux.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/alpha_processing.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/alpha_processing_mips_dsp_r2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/alpha_processing_neon.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/alpha_processing_sse2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/alpha_processing_sse41.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/cost.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/cost_mips32.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/cost_mips_dsp_r2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/cost_neon.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/cost_sse2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/cpu.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/dec.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/dec_clip_tables.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/dec_mips32.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/dec_mips_dsp_r2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/dec_msa.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/dec_neon.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/dec_sse2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/dec_sse41.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/enc_avx2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/enc_mips32.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/enc_mips_dsp_r2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/enc_msa.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/enc_neon.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/enc_sse2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/enc_sse41.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/filters.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/filters_mips_dsp_r2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/filters_msa.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/filters_neon.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/filters_sse2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/lossless.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/lossless_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/lossless_enc_mips32.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/lossless_enc_mips_dsp_r2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/lossless_enc_msa.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/lossless_enc_neon.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/lossless_enc_sse2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/lossless_enc_sse41.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/lossless_mips_dsp_r2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/lossless_msa.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/lossless_neon.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/lossless_sse2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/lossless_sse41.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/rescaler.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/rescaler_mips32.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/rescaler_mips_dsp_r2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/rescaler_msa.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/rescaler_neon.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/rescaler_sse2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/ssim.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/ssim_sse2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/upsampling.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/upsampling_mips_dsp_r2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/upsampling_msa.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/upsampling_neon.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/upsampling_sse2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/upsampling_sse41.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/yuv.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/yuv_mips32.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/yuv_mips_dsp_r2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/yuv_neon.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/yuv_sse2.c",
        freeImageRootDir .. "/Source/LibWebP/src/dsp/yuv_sse41.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/alpha_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/analysis_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/backward_references_cost_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/backward_references_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/config_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/cost_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/filter_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/frame_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/histogram_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/iterator_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/near_lossless_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/picture_csp_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/picture_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/picture_psnr_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/picture_rescale_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/picture_tools_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/predictor_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/quant_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/syntax_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/token_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/tree_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/vp8l_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/enc/webp_enc.c",
        freeImageRootDir .. "/Source/LibWebP/src/mux/anim_encode.c",
        freeImageRootDir .. "/Source/LibWebP/src/mux/muxedit.c",
        freeImageRootDir .. "/Source/LibWebP/src/mux/muxinternal.c",
        freeImageRootDir .. "/Source/LibWebP/src/mux/muxread.c",
        freeImageRootDir .. "/Source/LibWebP/src/utils/bit_reader_utils.c",
        freeImageRootDir .. "/Source/LibWebP/src/utils/bit_writer_utils.c",
        freeImageRootDir .. "/Source/LibWebP/src/utils/color_cache_utils.c",
        freeImageRootDir .. "/Source/LibWebP/src/utils/filters_utils.c",
        freeImageRootDir .. "/Source/LibWebP/src/utils/huffman_encode_utils.c",
        freeImageRootDir .. "/Source/LibWebP/src/utils/huffman_utils.c",
        freeImageRootDir .. "/Source/LibWebP/src/utils/quant_levels_dec_utils.c",
        freeImageRootDir .. "/Source/LibWebP/src/utils/quant_levels_utils.c",
        freeImageRootDir .. "/Source/LibWebP/src/utils/random_utils.c",
        freeImageRootDir .. "/Source/LibWebP/src/utils/rescaler_utils.c",
        freeImageRootDir .. "/Source/LibWebP/src/utils/thread_utils.c",
        freeImageRootDir .. "/Source/LibWebP/src/utils/utils.c",
        freeImageRootDir .. "/Source/LibJXR/image/decode/decode.c",
        freeImageRootDir .. "/Source/LibJXR/image/decode/JXRTranscode.c",
        freeImageRootDir .. "/Source/LibJXR/image/decode/postprocess.c",
        freeImageRootDir .. "/Source/LibJXR/image/decode/segdec.c",
        freeImageRootDir .. "/Source/LibJXR/image/decode/strdec.c",
        freeImageRootDir .. "/Source/LibJXR/image/decode/strdec_x86.c",
        freeImageRootDir .. "/Source/LibJXR/image/decode/strInvTransform.c",
        freeImageRootDir .. "/Source/LibJXR/image/decode/strPredQuantDec.c",
        freeImageRootDir .. "/Source/LibJXR/image/encode/encode.c",
        freeImageRootDir .. "/Source/LibJXR/image/encode/segenc.c",
        freeImageRootDir .. "/Source/LibJXR/image/encode/strenc.c",
        freeImageRootDir .. "/Source/LibJXR/image/encode/strenc_x86.c",
        freeImageRootDir .. "/Source/LibJXR/image/encode/strFwdTransform.c",
        freeImageRootDir .. "/Source/LibJXR/image/encode/strPredQuantEnc.c",
        freeImageRootDir .. "/Source/LibJXR/image/sys/adapthuff.c",
        freeImageRootDir .. "/Source/LibJXR/image/sys/image.c",
        freeImageRootDir .. "/Source/LibJXR/image/sys/strcodec.c",
        freeImageRootDir .. "/Source/LibJXR/image/sys/strPredQuant.c",
        freeImageRootDir .. "/Source/LibJXR/image/sys/strTransform.c",
        freeImageRootDir .. "/Source/LibJXR/jxrgluelib/JXRGlue.c",
        freeImageRootDir .. "/Source/LibJXR/jxrgluelib/JXRGlueJxr.c",
        freeImageRootDir .. "/Source/LibJXR/jxrgluelib/JXRGluePFC.c",
        freeImageRootDir .. "/Source/LibJXR/jxrgluelib/JXRMeta.c",
    }

    local includes =
    {
        freeImageRootDir .. "/Source",
        freeImageRootDir .. "/Source/LibJPEG",
        freeImageRootDir .. "/Source/ZLib",
        freeImageRootDir .. "/Source/OpenEXR",
        freeImageRootDir .. "/Source/OpenEXR/Half",
        freeImageRootDir .. "/Source/OpenEXR/Iex",
        freeImageRootDir .. "/Source/OpenEXR/IlmImf",
        freeImageRootDir .. "/Source/OpenEXR/IlmThread",
        freeImageRootDir .. "/Source/OpenEXR/Imath",
        freeImageRootDir .. "/Source/OpenEXR/IexMath",
        freeImageRootDir .. "/Source/LibRawLite",
        freeImageRootDir .. "/Source/LibRawLite/dcraw",
        freeImageRootDir .. "/Source/LibRawLite/internal",
        freeImageRootDir .. "/Source/LibRawLite/libraw",
        freeImageRootDir .. "/Source/LibRawLite/src",
        freeImageRootDir .. "/Source/LibWebP",
        freeImageRootDir .. "/Source/LibJXR",
        freeImageRootDir .. "/Source/LibJXR/common/include",
        freeImageRootDir .. "/Source/LibJXR/image/sys",
        freeImageRootDir .. "/Source/LibJXR/jxrgluelib"
    }

    local defines =
    {
        "DISABLE_PERF_MEASUREMENT=1",
        "PNG_ARM_NEON_OPT=0",
        "FREEIMAGE_LIB",
		"_LARGEFILE64_SOURCE=1",
        "OPJ_STATIC",
        "LIBRAW_NODLL"
    }

    return files, includes, defines
end

local function SetupSquish()
    local basePath = path.getabsolute("Cuttlefish/Cuttlefish", AssetConverter.dependencyDir)
    local squishRootDir = path.getabsolute("lib/libsquish", basePath)

    local files =
    {
        squishRootDir .. "/alpha.cpp",
        squishRootDir .. "/alpha.h",
        squishRootDir .. "/clusterfit.cpp",
        squishRootDir .. "/clusterfit.h",
        squishRootDir .. "/colourblock.cpp",
        squishRootDir .. "/colourblock.h",
        squishRootDir .. "/colourfit.cpp",
        squishRootDir .. "/colourfit.h",
        squishRootDir .. "/colourset.cpp",
        squishRootDir .. "/colourset.h",
        squishRootDir .. "/config.h",
        squishRootDir .. "/maths.cpp",
        squishRootDir .. "/maths.h",
        squishRootDir .. "/rangefit.cpp",
        squishRootDir .. "/rangefit.h",
        squishRootDir .. "/simd.h",
        squishRootDir .. "/simd_float.h",
        squishRootDir .. "/simd_sse.h",
        squishRootDir .. "/simd_ve.h",
        squishRootDir .. "/singlecolourfit.cpp",
        squishRootDir .. "/singlecolourfit.h",
        squishRootDir .. "/singlecolourlookup.inl",
        squishRootDir .. "/squish.cpp",
        squishRootDir .. "/squish.h"
    }

    local includes =
    {
        squishRootDir
    }

    local defines =
    {
        "CUTTLEFISH_HAS_S3TC"
    }

    return files, includes, defines
end

local function SetupBc7encRdo()
    local basePath = path.getabsolute("Cuttlefish/Cuttlefish", AssetConverter.dependencyDir)
    local bc7encRdoRootDir = path.getabsolute("lib/bc7enc_rdo", basePath)

    local files =
    {
        bc7encRdoRootDir .. "/bc7enc.cpp",
        bc7encRdoRootDir .. "/bc7enc.h",
        bc7encRdoRootDir .. "/rgbcx.cpp",
        bc7encRdoRootDir .. "/rgbcx.h",
        bc7encRdoRootDir .. "/rgbcx_table4.h",
    }

    local includes =
    {
        bc7encRdoRootDir
    }

    local defines =
    {
    }

    return files, includes, defines
end

local function SetupCompressonator()
    local basePath = path.getabsolute("Cuttlefish/Cuttlefish", AssetConverter.dependencyDir)
    local compressonatorRootDir = path.getabsolute("lib/compressonator", basePath)

    local files =
    {
        compressonatorRootDir .. "/cmp_core/shaders/bc4_encode_kernel.cpp",
        compressonatorRootDir .. "/cmp_core/shaders/bc4_encode_kernel.h",
        compressonatorRootDir .. "/cmp_core/shaders/bc5_encode_kernel.cpp",
        compressonatorRootDir .. "/cmp_core/shaders/bc5_encode_kernel.h",
        compressonatorRootDir .. "/cmp_core/shaders/bc6_encode_kernel.cpp",
        compressonatorRootDir .. "/cmp_core/shaders/bc6_encode_kernel.h"
    }

    local includes =
    {
        compressonatorRootDir .. "/cmp_core/source",
        compressonatorRootDir .. "/cmp_core/shaders"
    }

    local defines =
    {
    }

    return files, includes, defines
end

local function SetupLib()
    local basePath = path.getabsolute("Cuttlefish/Cuttlefish", AssetConverter.dependencyDir)
    local dependencies = { "glm" }
    local defines = { "_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS", "_SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS" }

    ProjectTemplate("Cuttlefish", "StaticLib", nil, AssetConverter.binDir, dependencies, defines)

    local sourceDir = path.getabsolute("lib/src", basePath)
    local includeDir = path.getabsolute("lib/include", basePath)

    local files =
    {
        -- Include Files
        includeDir .. "/**.h",
        includeDir .. "/**.hpp",

        -- Source Files
        sourceDir .. "/**.h",
        sourceDir .. "/**.hpp",
        sourceDir .. "/**.c",
        sourceDir .. "/**.cpp",
    }

    local freeImageFiles, freeImageIncludes, freeImageDefines = SetupFreeImage()
    local squishFiles, squishIncludes, squishDefines = SetupSquish()
    local bc7encRdoFiles, bc7encRdoIncludes, bc7encRdoDefines = SetupBc7encRdo()
    local compressonatorFiles, compressonatorIncludes, compressonatorDefines = SetupCompressonator()
    AddFiles({ files, freeImageFiles, squishFiles, bc7encRdoFiles, compressonatorFiles })

    AddIncludeDirs( { includeDir, freeImageIncludes, squishIncludes, bc7encRdoIncludes, compressonatorIncludes } )

    local defines = { "CUTTLEFISH_BUILD", "CUTTLEFISH_ISPC=0" }
    AddDefines({ defines, freeImageDefines, squishDefines, bc7encRdoDefines, compressonatorDefines })

    local exportFile = path.getabsolute("cmake/templates/NoExport.h", basePath)
    local copyToExportFilePath = path.getabsolute("lib/include/cuttlefish/Export.h", basePath)
    ok, err = os.copyfile(exportFile, copyToExportFilePath)

    if ok == nil then
        error("Failed to copy Cuttlefish Export File. " .. err)
    end

    warnings "Off"
end
SetupLib()

local function Include()
    local basePath = path.getabsolute("Cuttlefish/Cuttlefish", AssetConverter.dependencyDir)
    local sourceDir = path.getabsolute("lib/src", basePath)
    local includeDir = path.getabsolute("lib/include", basePath)

    AddIncludeDirs({ sourceDir, includeDir })

    AddDefines("CUTTLEFISH_BUILD")
    AddLinks("Cuttlefish")
end
CreateDep("cuttlefish", Include)