name: Build

on:
  push:
  workflow_dispatch:

jobs:
#  call-windows-build:
#    name: Windows Build
#    uses: novusengine/Workflows/.github/workflows/win-build.yml@master
#    with:
#      project: AssetConverter

  call-linux-build:
    name: Linux Build
    uses: novusengine/Workflows/.github/workflows/linux-build.yml@master
    with:
      project: AssetConverter
      build-types: Debug,RelDebug