name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [
          #win, 
          linux
        ]

    name: ${{ matrix.os }} build
    uses: ./.github/workflows/${{ matrix.os }}-build.yml